pipeline
{
    agent{label 'dev-server'}
    environment{
        NAME = "rohit"
    }
    tools {
        git 'Default'
        maven 'mymaven'
    }
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package'
                echo "hello $NAME"
            }
            post {
                success {
                    // One or more steps need to be included within each condition's block.
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}