pipeline
{
    agent{label 'dev-server'}
    tools {
        git 'Default'
        maven 'mymaven'
    }
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package'
            }
            post {
                success {
                    // One or more steps need to be included within each condition's block.
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
}