pipeline
{
    agent{label 'dev-server'}
    environment{
        NAME = "rohit"
    }
    parameters {
        string defaultValue: 'Rohit', name: 'FirstN'
        string defaultValue: 'Kalyan', name: 'SecondN'
    }

    tools {
        git 'Default'
        maven 'mymaven'
    }
    stages{
        stage('build'){
            steps{
                sh 'mvn clean package'
                echo "My first name is ${params.FirstN}"
                echo "My Second name is ${params.SecondN}"
            }
            post {
                success {
                    // One or more steps need to be included within each condition's block.
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}